top_srcdir   = /home/vincent/apache_benchmark_thread
top_builddir = /home/vincent/apache_benchmark_thread
srcdir       = /home/vincent/apache_benchmark_thread/os/unix
builddir     = /home/vincent/apache_benchmark_thread/os/unix
VPATH        = /home/vincent/apache_benchmark_thread/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
