top_srcdir   = /home/vincent/apache_benchmark_thread
top_builddir = /home/vincent/apache_benchmark_thread
srcdir       = /home/vincent/apache_benchmark_thread/modules
builddir     = /home/vincent/apache_benchmark_thread/modules
VPATH        = /home/vincent/apache_benchmark_thread/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

