top_srcdir   = /home/vincent/apache_benchmark_thread
top_builddir = /home/vincent/apache_benchmark_thread
srcdir       = /home/vincent/apache_benchmark_thread/os
builddir     = /home/vincent/apache_benchmark_thread/os
VPATH        = /home/vincent/apache_benchmark_thread/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
