top_srcdir   = /home/vincent/apache_benchmark_thread
top_builddir = /home/vincent/apache_benchmark_thread
srcdir       = /home/vincent/apache_benchmark_thread/srclib
builddir     = /home/vincent/apache_benchmark_thread/srclib
VPATH        = /home/vincent/apache_benchmark_thread/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
