top_srcdir   = /usr/src/mtcp/apps/apache_benchmark_deprecated
top_builddir = /usr/src/mtcp/apps/apache_benchmark_deprecated
srcdir       = /usr/src/mtcp/apps/apache_benchmark_deprecated/modules/ssl
builddir     = /usr/src/mtcp/apps/apache_benchmark_deprecated/modules/ssl
VPATH        = /usr/src/mtcp/apps/apache_benchmark_deprecated/modules/ssl
